// export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
// export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
// export const CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS';
// export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const TEST_ACTION = 'test_action';
export const FETCH_DOCUMENTS_REQUEST = 'FETCH_DOCUMENTS_REQUEST';
